= Paralela 24b

== Glossary
1) Programación serial: En la programación seriel, las tareas se ejecutan secuencialmente, es decir, una tras otra.

2) Programación concurrente: Es todo aquello que no es serial, es decir, las tareas se ejecutan de manera simultánea o alternada. Sin embatgo, no todo lo concurrente es paralelo.

3) Programación paralela: Es un subconjunto de la programación concurrente. Las tareas se ejecutan "una al lado de la otra", es decir, de manera simultánea.

4) Concurrencia de tareas: Es la capacidad que tiene el programa para ejecutar varias tareas al mismo tiempo. Esto no solo implica que las tareas se ejecuten de manera simultánea, sino que pueden intercalarse entre sí.

5) Paralelismo de datos: Es una técnica que se usa en programación paralela para dividir/distribuir los datos y operarlos al mismo tiempo

6) Hilo de ejecución: Es una tarea/rutina que se ejecuta de manera independiente a otras.

7) Indeterminismo: No se puede predecir el orden en el que serán ejecutadas las tareas/procesos/instrucciones en un programa concurrente

8) Memoria privada y compartida: La memoria privada se refiere a los datos, agrupados generalmente en alguna estructura, que son únicamente accesibles por un hilo de ejecución en particular. Por otra parte, la memoria compartida son aquellos datos que son accesidos por varios hilos de ejecución y es el mismo espacio de memoria.

9) Espera activa: Es una técnica que se para que un hilo de ejecución espere a que otro hilo de ejecución termine de ejecutarse. (No usar)

10) Condición de carrera: Es un problema que se presenta en la programación concurrente cuando dos o más hilos de ejecución intentan acceder a un recurso compartido al mismo tiempo.

11) Control de concurrencia: Es una técnica que se usa para evitar que dos o más hilos de ejecución accedan a un recurso compartido al mismo tiempo.

12) Seguridad condicional:

13) Exclusión mutua:

14) Semáforo:

15) Barrera:

16) Variable de condición:

17) Candado de lectura y escritura:

18) Descomposición:

19) Mapeo:

20) Incremento de velocidad:

21) Comunicación punto a punto entre procesos:

22) Comunicación colectiva entre procesos:

23) Reducción: